### ISSUE TITLE
Docker image version is not up-to-date

### ISSUE THREAD

**Issue by emillg** [caicloud/event_exporter#16]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Docker image version is still v0.0.1

**What you expected to happen**:
Docker image version is v0.1.0

**How to reproduce it (as minimally and precisely as possible)**:
Run ```docker pull cargo.caicloud.io/sysinfra/event-exporter```
Then start the container, the log says version is 0.0.1
```
time="2019-06-20T14:09:54+08:00" level=info msg="start event store..." source="store.go:110" 
time="2019-06-20T14:09:54+08:00" level=info msg="Starting event_exporter (version=v0.0.1, branch=doc, revision=4bc2df81dbed60cd33c379f6eabe4e3b8bcd6dac)" source="main.go:98" 
time="2019-06-20T14:09:54+08:00" level=info msg="Build context (go=go1.7.3, user=vagrant@vagrant-ubuntu-trusty-64, date=20161122-03:59:17)" source="main.go:99" 
time="2019-06-20T14:09:54+08:00" level=info msg="Listening on :9102" source="main.go:106"
```

**Anything else we need to know?**:
Would be nice to be able to run ```docker pull cargo.caicloud.io/sysinfra/event-exporter:v0.1.0```

**Comment by supereagle** [comment]
@emillg  Thanks for reporting this bug. `version=v0.0.1` is the version of Prometheus, it is not the version of event-exporter, it does not effect the function. Of course, I will fix this bug.

**Comment by emillg** [comment]
@supereagle Thanks. Do we have a docker image available now that contains this change https://github.com/caicloud/event_exporter/commit/61627488e241b415160ccc77b22e41a1d49bf808? We really need this feature.

**Comment by supereagle** [comment]
> @emillg Thanks for reporting this bug. `version=v0.0.1` is the version of Prometheus, it is not the version of event-exporter, it does not effect the function. Of course, I will fix this bug.

Sorry, I misunderstand your problem. You used the latest image, which version is still `v0.0.1`.

I have pushed an image `supereagle/event-exporter:v0.1.0` based on released tag [v0.1.0](https://github.com/caicloud/event_exporter/releases/tag/v0.1.0).

**Comment by emillg** [comment]
@supereagle Thanks for your help! I tried `supereagle/event-exporter:v0.1.0` but the pod can not start now.

```
  Normal   Pulled     67s (x4 over 115s)  kubelet, 10.112.234.62  Successfully pulled image "supereagle/event-exporter:v0.1.0"
  Normal   Created    67s (x4 over 115s)  kubelet, 10.112.234.62  Created container
  Warning  Failed     67s (x4 over 115s)  kubelet, 10.112.234.62  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/event_exporter\": stat /event_exporter: no such file or directory": unknown
  Warning  BackOff    31s (x8 over 113s)  kubelet, 10.112.234.62  Back-off restarting failed container
```

My yaml file looks like
```
    spec:
      serviceAccountName: kube-event-exporter
      containers:
      - name: kube-event-exporter
        image: supereagle/event-exporter:v0.1.0
        imagePullPolicy: Always
        command: ["/event_exporter"]
        ports:
        - containerPort: 9102
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 5m
            memory: 5Mi
```
