### ISSUE TITLE
Deploy event_exporter to Kubernetes cluster NO Metrics in Prometheus

### ISSUE THREAD

**Issue by Sallyan** [caicloud/event_exporter#34]
This event_exporter is nice! We would like to use this to monitoring our cluster behavior and health. 
Try to deploy it in cluster with following: 
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-exporter-sa
  namespace: kyma-system
  labels:
    app: event-exporter
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: event-exporter 
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: event-exporter-rb
  labels:
    app: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-exporter
subjects:
- kind: ServiceAccount
  name: event-exporter-sa
  namespace: kyma-system
```
**Deployment**
```
{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "labels": {
         "name": "event-exporter"
      },
      "name": "event-exporter"
   },
   "spec": {
      "replicas": 1,
      "revisionHistoryLimit": 2,
      "selector": {
         "matchLabels": {
            "app": "event-exporter"
         }
      },
      "strategy": {
         "type": "RollingUpdate"
      },
      "template": {
         "metadata": {
            "annotations": {
               "prometheus.io/path": "/metrics",
               "prometheus.io/port": "9102",
               "prometheus.io/scrape": "true"
            },
            "labels": {
               "app": "event-exporter",
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "./event_exporter"
                  ],
                  "env": [ ],
                  "image": "caicloud/event-exporter:v0.2.0",
                  "imagePullPolicy": "Always",
                  "name": "event-exporter",
                  "ports": [
                     {
                        "containerPort": 9102,
                        "name": "http"
                     }
                  ],
                  "resources": {
                     "limits": {
                        "memory": "100Mi"
                     },
                     "requests": {
                        "memory": "40Mi"
                     }
                  }
               }
            ],
            "serviceAccountName": "event-exporter-sa",
            "terminationGracePeriodSeconds": 30
         }
      }
   }
}
```
**Service**
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/scrape":"true"},"labels":{"name":"event-exporter"},"name":"event-exporter","namespace":"kyma-system"},"spec":{"ports":[{"name":"http","port":80,"targetPort":9102}],"selector":{"app":"event-exporter"}}}
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-04-16T15:53:31Z"
  labels:
    name: event-exporter
  name: event-exporter
  namespace: kyma-system
spec:
  clusterIP: 1*****
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9102
  selector:
    app: event-exporter
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
In event-exporter container, it shows error like this
```
INFO  0417-02:21:32.480+00 store.go:110 | start event store...
INFO  0417-02:21:32.480+00 main.go:105 | Starting event_exporter (version=v0.0.1, branch=master, revision=6590adfed64518de2429d2a3becc588671704380)
INFO  0417-02:21:32.481+00 main.go:106 | Build context (go=go1.12.9, user=root@26f1ca322850, date=20190906-09:51:13)
INFO  0417-02:21:32.481+00 main.go:113 | Listening on :9102
E0417 02:21:32.482142       1 reflector.go:126] github.com/caicloud/event_exporter/store.go:111: Failed to list *v1.Event: Get https://100.64.0.1:443/api/v1/events?limit=500&resourceVersion=0: dial tcp 100.64.0.1:443: connect: connection refused
E0417 02:21:33.486319       1 reflector.go:126] github.com/caicloud/event_exporter/store.go:111: Failed to list *v1.Event: Get https://100.64.0.1:443/api/v1/events?limit=500&resourceVersion=0: dial tcp 100.64.0.1:443: connect: connection refused
E0417 02:21:34.487073       1 reflector.go:126] github.com/caicloud/event_exporter/store.go:111: Failed to list *v1.Event: Get https://100.64.0.1:443/api/v1/events?limit=500&resourceVersion=0: dial tcp 100.64.0.1:443: connect: connection refused
```
Open Prometheus metrics http://localhost:9090/metrics, cannot search out "kubernetes_events"
